addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8

language: cpp

compiler:
  - g++-4.8

before_install:
  - sudo add-apt-repository ppa:comp-phys/stable -y 
  - sudo apt-get update 
  - sudo apt-get install liblapack-dev
  - sudo apt-get install libblas-dev 
  - sudo apt-get install libboost-dev 
  - sudo apt-get install libarmadillo-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - make

os:
  - linux
