addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8

language: cpp

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install liblapack-dev && sudo apt-get install libblas-dev && sudo apt-get install libboost-dev && sudo apt-get install libarmadillo-dev ; fi

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - make

os:
  - linux
