language: cpp

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install liblapack-dev && sudo apt-get install libblas-dev && sudo apt-get install libboost-dev && sudo apt-get install libarmadillo-dev ; fi

script:

  - make
os:
  - linux
